stages:
  - build
  - push

variables:
  IMAGE_TAG: registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t $IMAGE_TAG .
  only:
    - main

push-image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $IMAGE_TAG
  only:
    - main

